kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efssharedvolume
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-class
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: efspv1